# desenvolvimento local
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

COPY src/src.csproj App/

WORKDIR /App
RUN dotnet restore

COPY src/. .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /App
COPY --from=build-env /App/out ./

ENTRYPOINT ["dotnet", "src.dll"]